title: CS 195
description: "CS 195: Social Implications of Computer Technology"
collections_dir: collections

url: "sp23.cs195.org"
edstem: https://edstem.org/us/courses/35154
ed_zoom_link: https://edstem.org/us/courses/35154/discussion/2394817
term: Spring 2023

theme: minima

exclude:
  - .venv
  - .direnv
  - scripts

collections:
  - cs195_readings
  - csH195_discussions

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true
